### ISSUE TITLE
Emp_Code is not returning in AddEmployee API

### ISSUE THREAD

**Issue by zeeshanmakeen** [TheAlphaSchoolSystemPTYLTD/employee-hr#14]
Hi,

Can you help me I am not receiving **emp_code** when calling **AddEmployee** API. The employee record is creating correctly with Employee Code auto generated on web portal. But I am receiving empty **emp_code** in API response when called AddEmployee api. 

I need this emp_code for further processing.

Thanks

**Comment by bradftass** [comment]
Hi, this will be resolved in v58.04.201 due for release this week.

Regards,
Brad Fleming
