### ISSUE TITLE
Permission Roles

### ISSUE THREAD

**Issue by i-am-ari** [TheAlphaSchoolSystemPTYLTD/employee-hr#20]
Employee records can store Personally Identifiable Data such as Drivers Licenses, Passports, etc.

Would it be possible for this API (and the Students API) to have a permission role placed over it in the TASS software down to the permission point to only allow certain fields to be pulled through the API? This would prevent intermediary supply chain companies (such as Wonde) from trying to pull super sensitive fields.

**Comment by scottetass** [comment]
Hi Ari,

Granular permissions for fields returned in the API are not currently possible.
However, this is definitely something that will be implemented in our new API offering coming later this year.

Regards, Scott
