### ISSUE TITLE
EmployeeHR - addEmployee

### ISSUE THREAD

**Issue by jwong-star** [TheAlphaSchoolSystemPTYLTD/employee-hr#26]
Hi,

We are planning to use the EmployeeHR API to add new staff.

There are some information in github but they are not detailed enough.

For example, at the end of the following web page, it does not show us how to pass the following parameters to API:

Token, salutation_flag, surname_text, given_names_text and so on.

https://github.com/TheAlphaSchoolSystemPTYLTD/employee-hr/blob/master/addEmployee.md

We are planning to use HTML or C#.

Do you have sample codes that we can study? Thank you.

**Comment by bradftass** [comment]
Hi,

Thank you for commenting.  Please see the API Introduction documentation that will assist you in generating an API call:
https://github.com/TheAlphaSchoolSystemPTYLTD/api-introduction

I will close this now, but please feel free to raise a new issue if there is further information you require.
