### ISSUE TITLE
Adding employee email fields issue/bug

### ISSUE THREAD

**Issue by CTO4556** [TheAlphaSchoolSystemPTYLTD/employee-hr#27]
Hi there

We are adding employees via this API and we are finding there is no distinction between e_mail and school_email.

e_mail is not being accepted to place the personal email into the staff record.

If we pass school_email, it populates both school and personal email.

Can you let me know if we are doing something wrong?

Chris

**Comment by scottetass** [comment]
Hi Chris,

Some work regarding e_mail and school_email is coming in the April release. 

I have tested this in our development environment, and everything appears to be working as expected now with e_mail and school_email.

If the problem still persists for you after the April release, then please update this issue.

Regards, Scott

**Comment by CTO4556** [comment]
I will investigate - do you know what release version this applies to?

Also, have you done any investigation into the significant issues with data uploader section on the Country code validation error when we try to update simple details against an employee?

The STP logic and State entries does not align with the documentation that we can see - hence we get errors all over the show. This was from a ticket we had with TASS as feedback, but it is of no use to us from a dev perspective as it still doesn't work:

From TASS Support:
-----
The API has different requirements for STP on and off.
I will put in a request to the development team to see if they can make the documentation clearer.
I can confirm the requirements for the fields based on the documentation however I cannot confirm the initial intent as this is outside the scope of TASS support.
----

From our developer:
It would always be present when we see new records, can confirm in the code because that's how they told us it has to work in order to create an employee (because you have to have an address to make a new record). So the short answer is: yes, most if not all would have a country code so have to send state_text but with an empty string? I guess I can try that but that seems a little absurd, surely the ATO needs that part of the address for STP 2.0 uploads?
Is that the intent from what we read below?
---

Essentially if you can point us in the right direction as to how to update a record it would be appreciated as its getting rather long in the tooth and we cannot seem to find someone who actually understands how this API is meant to work?

Chris

**Comment by scottetass** [comment]
The release version with the email changes is 59.04.100.

I've just seen your other ticket regarding your country_code / post_code problem. I will take another look and see if I can find out what's going on.

**Comment by CTO4556** [comment]
Thank you - this is in the Data Upload Utility - the logic is counterintuitive and we haven't been able to get it to work properly.
