### ISSUE TITLE
HR Data post/Get - but can we do updates like PATCH or PUT

### ISSUE THREAD

**Issue by mjaniszewski1** [TheAlphaSchoolSystemPTYLTD/employee-hr#28]
Quick question, with the HR add employee - does it support updating once a record is created?

**Comment by leonseremelis-tass** [comment]
Hi, thanks for the question, there is no functionality to update existing employee details at this stage.

**Comment by mjaniszewski1** [comment]
Thanks Leon,

But also, to clarify it can create an employee one time with general tab data, address tab and next of kin tab?



Martin Janiszewski
ICT Systems Manager
St Mary Star of the Sea College
t: +61242286011
e: ***@***.***
w: www.stmarys.nsw.edu.au
a: 15 Harbour St Wollongong NSW 2500
This e-mail, and any attachment, is confidential. If you are not the intended recipient, please delete it from your system, do not use or disclose the information in any way, and notify the sender immediately. Any views expressed in this message are those of the individual sender and may not be the views of St Mary Star of the Sea College, unless specifically stated. No warranty is made that the e-mail or attachment(s) are free from computer viruses or other defects.
________________________________
From: Leon Seremelis ***@***.***>
Sent: Tuesday, 29 August 2023 3:06 PM
To: TheAlphaSchoolSystemPTYLTD/employee-hr ***@***.***>
Cc: Martin Janiszewski ***@***.***>; Author ***@***.***>
Subject: [EXT] | Re: [TheAlphaSchoolSystemPTYLTD/employee-hr] HR Data post/Get - but can we do updates like PATCH or PUT (Issue #28)

Caution: This is an external email and may be malicious. Please take care when clicking links, opening attachments or following directions.


Hi, thanks for the question, there is no functionality to update existing employee details at this stage.

**Comment by leonseremelis-tass** [comment]
Yes that is correct, data from all three of the tabs can be inserted into the record so long as the data is included in the one call.
