### ISSUE TITLE
first_name added to response? 

### ISSUE THREAD

**Issue by cwool** [TheAlphaSchoolSystemPTYLTD/employee-hr#29]
Hi,

Would it be possible to have the employees "First Name" added to the response for the getEmployeesDetails.md method?

<img width="157" alt="Screenshot 2023-11-08 at 4 25 46 pm" src="https://github.com/TheAlphaSchoolSystemPTYLTD/employee-hr/assets/70622121/66f30d31-5e98-459c-86bc-0b1b49ecc0a7">

**Comment by scottetass** [comment]
Hi cwool,

first_name has been added to the response for the March 2024 release.

Thanks, Scott
