### ISSUE TITLE
Multiple employee codes as a parameter for syncing photos in smaller amounts

### ISSUE THREAD

**Issue by cwool** [TheAlphaSchoolSystemPTYLTD/employee-hr#31]
We are trying to sync photos for employees at Knox Grammar but there doesn’t seem to be any way to split out the requests as it’s either one staff member or all of them from both employee-hr/getEmployeesDetails.

Any suggestions? If possible we’d love to be able to pass across multiple employee_codes and do 50-100 per request but would be happy with any way to not have to sync all the photos in one call or one call for every employee.

**Comment by scottetass** [comment]
Hi cwool,

Thanks for the suggestion. We agree it would be a good option to have and are currently deciding when to schedule to change. Once we have it scheduled in a release, I will get back to you with the details.

Regards, Scott

**Comment by scottetass** [comment]
Hi cwool,

This has been scheduled and will be in the 59.04.200 release in April.

The code parameter will cater for different scenarios - leave it blank for all employees, provide one or more codes in a comma delimited list.

Thanks, Scott
