### ISSUE TITLE
unable to post multiple employees in the same file to TASS HR

### ISSUE THREAD

**Issue by S1mps0** [TheAlphaSchoolSystemPTYLTD/employee-hr#32]
We are able to post individual employee records to TASS via the public API but not multiple ones.  There is no error message and the first record posts successfully but does not return a success or failure message.  The subsequent records do not load and do not return a failure message.  Does anyone have any ideas what we might be doing wrong here?

**Comment by scottetass** [comment]
Hi,

Are you able to supply me with the request json that you used for the call and also the response from the server?
You can obfuscate any employee details in the request payload to avoid exposing them, I'm more just interested in the construct of the json.

I ran a test in our dev environment and it ran ok and returned a success message:

```
"success": "You successfully saved 2 employee(s)."
```

Regards, Scott

**Comment by S1mps0** [comment]
Hi Scott

I have spoken to our developer Jerry Wong and he has told me that he is not
using JSON to run the employee HR API, and that we are using the TASS.web
version to run the API.

Can you advise whether this has an impact on the API result?  I will ask
Jerry to speak to you directly to explain the process he has followed in
creating the routine to use the API to create new employees.

Regards

Peter

**Comment by scottetass** [comment]
Hi Peter,

I've been in contact and trying to work through the details with him. Hopefully we can get it sorted soon.

Thanks, Scott

**Comment by S1mps0** [comment]
Hi Scott

Thanks - we really appreciate your help

Regards

Peter

**Comment by scottetass** [comment]
This has been sorted out now with Jerry. Closing the issue.
