### ISSUE TITLE
First Name for getEmployeesDetails endpoint

### ISSUE THREAD

**Issue by igroenewald** [TheAlphaSchoolSystemPTYLTD/employee-hr#34]
Hi Tass,

It is my understanding that the enhancement to implement ‘first_name’ into the ‘general’ node within the getEmployeesDetails endpoint of the Employee/HR API has been completed and will be in your v59.03.200 release around mid-end of March. I don't see any changes in the getEmployeesDetails endpoint.

Do you know whether this has been released?

Thank you
Irene

**Comment by scottetass** [comment]
Hi Irene,

This change was done in 59.03.200 and has no conditions around the return of the field so it should be there in the results from the API call.

![image](https://github.com/user-attachments/assets/1e41d705-43ba-49ea-9f89-b65f856dd154)

Thanks, Scott
