### ISSUE TITLE
Getting 401 Not Authorized response

### ISSUE THREAD

**Issue by oliverhaskell** [TheAlphaSchoolSystemPTYLTD/employee-hr#7]
Hi,

I'm attempting to access the API at two schools in Australia, but both are giving me the "401 - Unauthorized: Access is denied due to invalid credentials" response when I try to access the GetEmployeesDetails & GetStudentsDetails methods.

I have used the encryptDecrypt.cs code from the GIT repo verbatim to generate the URL for the GET, using the token value provided by the schools, along with the appcode & companycode for each method.

What else should I be looking at to work out what I'm doing wrong, please?

Many thanks,
Oliver Haskell, CHQ Group Ltd

**Comment by jtc** [comment]
Hi Oliver,

Ask the schools to log in to TASS.web and go to System Admin > Utilities > API Gateway Maintenance > TASS APIs and click Log against the appropriate app code.

This should provide some more details and also allows them to "Print" an Excel file with the details to send to you.

Josh
(not a TASS employee)

**Comment by oliverhaskell** [comment]
Many thanks Josh, I'll try that!
Oliver

**Comment by oliverhaskell** [comment]
The log at one of the schools shows this: "The 3 parameter of the Mid function, which is now -1, must be a non-negative integer" ... is that helpful?
Oliver

**Comment by jtc** [comment]
Not anything I've seen before, will leave that one to TASS 😃

**Comment by oliverhaskell** [comment]
Issue solved - my fault, sorry!
The problem was a malformed JSON string for the parameters, with an equals sign instead of a colon, separating one of the key names from its value.
